version: '3.5'
    
services:
  
  db:
    image: mongo:3.4
  escrituracao-backend:
    image: node:8.1
    volumes:
      - ./src:/backend
    ports:
      - 7270:7270
    command: bash -c "cd /backend && npm i && npm start"

  notas-backend:
   image: jamesdbloom/mockserver:mockserver-5.5.1
   ports:
   - 7271:7271
   environment:
   - LOG_LEVEL=INFO
   volumes: 
    - ./notasmock:/tmp/notasmock
   command: bash -c "/opt/mockserver/run_mockserver.sh -serverPort 7271 -logLevel INFO -jvmOptions "-Dmockserver.propertyFile='/tmp/notasmock/mockserver.properties'""