version: '3.5'
    
services:
  db:
    image: mongo:3.4
  escrituracao-backend:
    image: node:8.1
    volumes:
      - ./src:/backend
    ports:
      - 7270:7270
    command: bash -c "cd /backend && npm i && npm start"
  notas-backend:
   image: jamesdbloom/mockserver:mockserver-5.5.1
   ports:
   - 7271:1080
   environment:
   - LOG_LEVEL=INFO